### ISSUE TITLE
Смена лицензии

### ISSUE THREAD

**Issue by dimzon** [garakh/kladrapi#14]
Все не настолько просто
1) сторонние контрибюторы проекта если таковые есть контрибютили под одной лицензией а вы ее поменяли
2) вчерашний снапшот есть и останется де-юре под двойной лицензией

**Comment by b1oki** [comment]
@dimzon 
Изучил вопрос. Согласно лицензии MIT, которая была ранее, производные произведения не обязаны распространяться на условиях первоначальной лицензии.
