### ISSUE TITLE
Проблема с withParents

### ISSUE THREAD

**Issue by kinolaev** [garakh/kladrapi#29]
Здравствуйте. Сегодня (возможно, в конце прошлой недели) появилась следующая проблема: withParents - и в режиме oneString, и в режиме формы - возвращает не все родительские объекты. Например:
1) в режиме одной строки на запрос "москва чертановская 2" возвращается объект типа building, но в parents нет объекта улицы,
2) в режиме формы на запрос "чертановская" в parents не возвращается город, только регион.
Однострочный режим можете проверить у себя на сайте в разделе примеров.
Спасибо.

**Comment by garakh** [comment]
Постараемся сегодня посмотреть, спасибо.

**Comment by kinolaev** [comment]
Проблема все еще очень актуальна, можете ли назвать приблизительные сроки решения? Спасибо.

**Comment by garakh** [comment]
А вы можете уточнить конкретный запрос к API.
Например http://kladr-api.ru/api.php?query=москва чертановская 2&oneString=true&withParent=1&limit=50

отдает корректные данные

**Comment by kinolaev** [comment]
посмотрите внимательнее свой пример, ответ сервиса некорректен: в parents объектов типа building нет улиц, а parents объекта типа улица нет города.

**Comment by kinolaev** [comment]
Здравствуйте, есть ли новости по данной проблеме?
Возможно, street не возвращается в parents building'ов только в городах федерального значения (Москва, Санкт-Петербург, Севастополь, Байконур). При этом в fullName улица есть.
Пробовал наугад несколько других городов, ответ верный.

**Comment by kinolaev** [comment]
Чтобы не забылось: в parents улиц городов федерального значения нет объектов городов (в fullName города есть)

**Comment by garakh** [comment]
Поправили

**Comment by kinolaev** [comment]
Плохо поправили)
1) Теперь в parents зданий есть улицы, но нет городов
2) В parents улиц городов так и нет
3) У улиц okato - null
Опять же, проблема касается только тех улиц и зданий, у которых в parents region === city (Москва, Санкт-Петербург, Севастополь, Байконур)

**Comment by garakh** [comment]
Да, вы правы.
Поправили.

У улиц okato - null — такие данные в базе ФИАС

**Comment by kinolaev** [comment]
Да, теперь все верно. Огромное спасибо за вашу работу.

P.S.: Мне okato улиц не нужно, но замечу, что его нет только в городах федерального значения...
