### ISSUE TITLE
Ошибка доступа заголовков при обращении к базе по Ajax

### ISSUE THREAD

**Issue by vUdav** [garakh/kladrapi#37]
Добрый день.
Пишу приложение под React. Решил написать свой компонент по обращению к базе через ajax. Get запрос уходит нормально (статс 200), но ничего не возвращает в ответ. Консоль показывает ошибку заголовков **_XMLHttpRequest cannot load http://kladr-api.ru/api.php?query=%D0%BC&contentType=city&limit=5&token=51dfe5d42fb2b43e3300006e. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access._**

**Comment by garakh** [comment]
Почитайте про Access-Control-Allow-Origin и JSONP
